language: node_js
node_js:
  - '8'
cache: yarn
notifications:
  email: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn lint
  - yarn test
# deploy:
#   - provider: script
#     script: yarn deploy:development
#     skip_cleanup: true
#     on:
#       branch: development
#   - provider: script
#     script: yarn deploy:master
#     skip_cleanup: true
#     on:
#       branch: master
env:
  global:
    - EXP_USERNAME=serlo-org
    - secure: GykLI4h26y33AI/3Axejw6QTeWaDJX221HKPiAi9vMfBzXUYBRrDjLwjR6JFKuc75WJZThAISrijnprunkNKwtTTV2qSSZ5i8PsvgedYOrYMLpYLn2fLWVKBiHC5rpgKujmktIq/TE6voOystGyBZic1Q14W9GWnWJFHpZpqxndsj9QoOdEhsugvOklyABKjxFp4ATmO4qfWKBBSxmFJQv8r6m9dpw6v9WA34uOl0WPurgGAq8xB7EKJUqLDd+HHEB0OjQcFbHgT8zD1fi620/Ymp7lIa7JXW3soiy4kGn/kKN++zoHrlaQQVB5uBDWQYxtAtXhWYP7mYG0DGG/v5+JshsIPYo41ZgxBwjgsbO9o9kd4Uuz/0qQrJp/1m9WzwRSDx5gMRTX4ja7uy5dZo6crO9q5/iumjYwPEzapnSovu9s76zclrQFRGpl7zYfwCkRgUPfMAeOz3Yne+lYaehvJ07P+PQX+OtIAwNiTn6eROuv2hBNetht8grfXenfgQEkXw58F5WpwMp8ZieuxsJw2Od6UzJtAxEsaTT4suL4YqnBYh0UgIBj9YqYmlqcRq3pNZoyd3rmoKzGxGS/XiK82RUEVxbtyKL66bg6VY4Dzv26SdfxCpUiWVkYt17+px09PRoH5NWEHeGHxWe+pcOxsCRb3jcrdKUyZRUJd4Lg=
