js: &js
  docker:
    - image: circleci/node:10

yarn_restore_cache: &yarn_restore_cache
  keys:
    - yarn-v1-{{ checksum "yarn.lock" }}
    - yarn-v1-
yarn_save_cache: &yarn_save_cache
  key: yarn-v1-{{ checksum "yarn.lock" }}
  paths:
    - ~/.cache/yarn
yarn_install: &yarn_install
  command: yarn --frozen-lockfile

version: 2.1
jobs:
  test:
    <<: *js
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_restore_cache
      - run:
          <<: *yarn_install
      - save_cache:
          <<: *yarn_save_cache
      - run:
          command: yarn test
  lint:
    <<: *js
    steps:
      - checkout
      - restore_cache:
          <<: *yarn_restore_cache
      - run:
          <<: *yarn_install
      - save_cache:
          <<: *yarn_save_cache
      - run:
          command: yarn lint

workflows:
  version: 2
  workflow:
    jobs:
      - lint
      - test
